apiVersion: v1
kind: Service
metadata:
  name: cicd-kubernetes-pipeline
  namespace: cicd-demo
  labels:
    app.kubernetes.io/name: cicd-kubernetes-pipeline
    app.kubernetes.io/component: web
    app.kubernetes.io/part-of: sre-portfolio
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: cicd-kubernetes-pipeline
    app.kubernetes.io/component: web
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
